//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tals.ProBono.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string AuditType { get; set; }
        public string UserName { get; set; }
        public System.DateTime AuditDate { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
