//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Tals.ProBono.Domain.Filters;

namespace Tals.ProBono.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class Category
    {
        //public Category()
        //{
        //    this.Questions = new HashSet<Question>();
        //    this.Subscriptions = new HashSet<Subscription>();
        //}
    
        public int Id { get; set; }

        [Required]
        [StringLength(300)]
        [DisplayName("Category Name")]
        public string CategoryName { get; set; }
        
        [Required]
        [StringLength(500)]
        [DisplayName("Short Description")]
        public string ShortDescription { get; set; }

        [StringLength(1000)]
        [DisplayName("Long Description")]
        public string LongDescription { get; set; }

        [DisplayName("Sort Order")]
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }

        [NotMapped]
        public Question LastQuestion
        {
            get { return Questions.AsQueryable().NotTaken().Active().OrderByDescending(x => x.CreatedDate).FirstOrDefault(); }
        }

        public bool IsSubscribed(string userName)
        {
            return Subscriptions.Any(s => s.UserName == userName);
        }
    }
}
