//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tals.ProBono.Domain.Entities
{
    using System;
    using System.Collections.Generic;

    public class ReferralOrg
    {

        public int Id { get; set; }
        public string OrgName { get; set; }

        public virtual ICollection<Question> Questions { get; set; }
    }
}
