//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tals.ProBono.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tals.ProBono.Resources.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been here before? Sign in to see your answers or ask a new question:.
        /// </summary>
        public static string BeenHereBefore {
            get {
                return ResourceManager.GetString("BeenHereBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Users Sign In.
        /// </summary>
        public static string ExistingUserLink {
            get {
                return ResourceManager.GetString("ExistingUserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &quot;Register as a New User&quot; button below to find out if you can get help. You will be asked questions about yourself, your income, and your legal problem. All of your answers will be kept secret..
        /// </summary>
        public static string HowItWorks1 {
            get {
                return ResourceManager.GetString("HowItWorks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a username and password to use on this website. This keeps your information confidential and saves your question..
        /// </summary>
        public static string HowItWorks2 {
            get {
                return ResourceManager.GetString("HowItWorks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with your username and password..
        /// </summary>
        public static string HowItWorks3 {
            get {
                return ResourceManager.GetString("HowItWorks3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in your question. If you have a court date or other deadline coming up, we can&apos;t promise you will get an answer before that time..
        /// </summary>
        public static string HowItWorks4 {
            get {
                return ResourceManager.GetString("HowItWorks4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you an e-mail when a lawyer answers your question..
        /// </summary>
        public static string HowItWorks5 {
            get {
                return ResourceManager.GetString("HowItWorks5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log back into this website and read the lawyer&apos;s advice. If it isn&apos;t clear, you can ask more questions..
        /// </summary>
        public static string HowItWorks6 {
            get {
                return ResourceManager.GetString("HowItWorks6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{SiteName}} is a website where low-income people who have a civil legal problem in Washington State can get free legal advice from volunteer attorneys by creating an account and logging in to post their legal questions..
        /// </summary>
        public static string Intro1 {
            get {
                return ResourceManager.GetString("Intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get free legal advice through {{SiteName}}, you must first qualify for help..
        /// </summary>
        public static string Intro2 {
            get {
                return ResourceManager.GetString("Intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are a new user, please register:.
        /// </summary>
        public static string NewUserRegister {
            get {
                return ResourceManager.GetString("NewUserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a New User.
        /// </summary>
        public static string NewUserRegisterLink {
            get {
                return ResourceManager.GetString("NewUserRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {{SiteName}}!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
