//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tals.ProBono.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ask {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ask() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tals.ProBono.Resources.Resources.Views.Client.Ask", typeof(Ask).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your question about?.
        /// </summary>
        public static string AboutQuestion {
            get {
                return ResourceManager.GetString("AboutQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Question.
        /// </summary>
        public static string AskQuestion {
            get {
                return ResourceManager.GetString("AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this question is about an open legal case, what county is your case in? (leave blank if you do not have an open legal case).
        /// </summary>
        public static string CountyQuestion {
            get {
                return ResourceManager.GetString("CountyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might not get an answer to your question before your court date..
        /// </summary>
        public static string CourtDateMessage {
            get {
                return ResourceManager.GetString("CourtDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a court date, enter it here..
        /// </summary>
        public static string CourtDateQuestion {
            get {
                return ResourceManager.GetString("CourtDateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will ask a lawyer to answer you. This can take up to 14 days. We can&apos;t promise you will get an answer. If there is no answer after 14 days, we&apos;ll email you. If you don&apos;t have an email address, you will have to sign into your account to check for answers..
        /// </summary>
        public static string DurationMessage {
            get {
                return ResourceManager.GetString("DurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have questions about the lawyer&apos;s answer. You can ask follow-up questions about the answer..
        /// </summary>
        public static string FollowupMessage {
            get {
                return ResourceManager.GetString("FollowupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ask your question below and click &quot;Send&quot;:.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not know which category your legal issue is in, select &quot;Other&quot;..
        /// </summary>
        public static string KindHelp {
            get {
                return ResourceManager.GetString("KindHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o learn more about where your legal issue may fit or to receive general information about the law, visit {{SiteLink}}.
        /// </summary>
        public static string KindMoreInfo {
            get {
                return ResourceManager.GetString("KindMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind of Problem.
        /// </summary>
        public static string KindOfProblem {
            get {
                return ResourceManager.GetString("KindOfProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lawyer may need to ask you some questions before they can answer you. If so, we&apos;ll send you an email. If you don&apos;t have an email address, you will have to sign into your account to check for questions..
        /// </summary>
        public static string LawyerAnswerMessage {
            get {
                return ResourceManager.GetString("LawyerAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of the person or organization causing your legal problem? If you don&apos;t know, just leave it blank..
        /// </summary>
        public static string NameQuestion {
            get {
                return ResourceManager.GetString("NameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Question.
        /// </summary>
        public static string NewQuestion {
            get {
                return ResourceManager.GetString("NewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your question here:.
        /// </summary>
        public static string QuestionLabel {
            get {
                return ResourceManager.GetString("QuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short survey.
        /// </summary>
        public static string ShortSurvey {
            get {
                return ResourceManager.GetString("ShortSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take a moment to complete our {{SurveyLink}}. Your feedback is important to us..
        /// </summary>
        public static string SurveyMessage {
            get {
                return ResourceManager.GetString("SurveyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your question..
        /// </summary>
        public static string ThanksMessage {
            get {
                return ResourceManager.GetString("ThanksMessage", resourceCulture);
            }
        }
    }
}
