//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tals.ProBono.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SignUpStep1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignUpStep1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tals.ProBono.Resources.Resources.Views.Account.SignUpStep1", typeof(SignUpStep1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remember:.
        /// </summary>
        public static string PleaseRemember {
            get {
                return ResourceManager.GetString("PleaseRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no guarantee that a lawyer will answer your question. This website is one resource you can use to get help, but not a promise of help..
        /// </summary>
        public static string PleaseRememberItem1 {
            get {
                return ResourceManager.GetString("PleaseRememberItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have an emergency, contact the police or use the resources listed to the left of this page to find help..
        /// </summary>
        public static string PleaseRememberItem2 {
            get {
                return ResourceManager.GetString("PleaseRememberItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question will be up for 14 days. A lawyer could answer it right away, or after several days. Please check back to see if your question was answered..
        /// </summary>
        public static string PleaseRememberItem3 {
            get {
                return ResourceManager.GetString("PleaseRememberItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Signup.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only use this website if all of these things above are true. You must agree to tell the truth. We will keep your answers confidential..
        /// </summary>
        public static string TruthStatement {
            get {
                return ResourceManager.GetString("TruthStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will ask questions to make sure:.
        /// </summary>
        public static string WeWillAsk {
            get {
                return ResourceManager.GetString("WeWillAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a low income.
        /// </summary>
        public static string WeWillAskItem1 {
            get {
                return ResourceManager.GetString("WeWillAskItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at least {{MinimumAge}} years old.
        /// </summary>
        public static string WeWillAskItem2 {
            get {
                return ResourceManager.GetString("WeWillAskItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You live or have a problem in Washington State.
        /// </summary>
        public static string WeWillAskItem3 {
            get {
                return ResourceManager.GetString("WeWillAskItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your legal issue isn&apos;t one you could go to jail for.
        /// </summary>
        public static string WeWillAskItem4 {
            get {
                return ResourceManager.GetString("WeWillAskItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t already have a lawyer helping you with this problem.
        /// </summary>
        public static string WeWillAskItem5 {
            get {
                return ResourceManager.GetString("WeWillAskItem5", resourceCulture);
            }
        }
    }
}
