//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tals.ProBono.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SignUpStep6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignUpStep6() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tals.ProBono.Resources.Resources.Views.Account.SignUpStep6", typeof(SignUpStep6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter income for person #{{Num}}.
        /// </summary>
        public static string EnterForPerson {
            get {
                return ResourceManager.GetString("EnterForPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only numbers without signs. (Example: 1000).
        /// </summary>
        public static string EnterOnly {
            get {
                return ResourceManager.GetString("EnterOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every two weeks.
        /// </summary>
        public static string EveryTwoWeeks {
            get {
                return ResourceManager.GetString("EveryTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Often?.
        /// </summary>
        public static string HowOften {
            get {
                return ResourceManager.GetString("HowOften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income before taxes are taken out:.
        /// </summary>
        public static string IncomeBeforeTaxes {
            get {
                return ResourceManager.GetString("IncomeBeforeTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income is money you get from things like jobs and government benefits (like unemployment). Specify the income for you and for each person in your household..
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twice a month.
        /// </summary>
        public static string TwiceAMonth {
            get {
                return ResourceManager.GetString("TwiceAMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
    }
}
